# name: Test Base Image

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"

#       - name: Install test dependencies
#         run: pip install -r requirements-test.txt

#       - name: Build test image
#         run: docker build -t dagster-core:latest .

#       - name: Run tests
#         run: pytest tests/

name: Test Trigger Service

on:
  push:
    branches: [main]
    paths:
      - "trigger_service/**"
      - "tests/**"
      - "requirements.txt"
      - "Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - "trigger_service/**"
      - "tests/**"
      - "requirements.txt"
      - "Dockerfile"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx

      - name: Run tests
        run: pytest tests/

      - name: Build test image
        run: docker build -t dagster-trigger-service:test .

      - name: Test service startup
        run: |
          docker run -d --name test-service \
            -e DAGSTER_HOST=mock \
            -e DAGSTER_PORT=3000 \
            -e API_KEY=test_key \
            dagster-trigger-service:test
          sleep 5
          docker logs test-service
          docker rm -f test-service
